M48
; DRILL file {KiCad 7.0.9} date Sun Mar 24 10:40:42 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-24T10:40:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X5.2031Y-1.0016
X5.2031Y-1.1
X5.4Y-1.2969
X5.5969Y-1.0016
X5.5969Y-1.1
T0
M30
