M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-07-17T18:33:13-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-17T18:33:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.762
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.950
%
G90
G05
T1
X96.5Y-49.0
X96.5Y-51.0
X101.0Y-49.0
X101.0Y-51.0
T2
X87.0Y-47.0
X87.0Y-49.5
X87.0Y-52.0
M30
